# Generated by Django 4.2 on 2024-07-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='guideId',
            field=models.IntegerField(null=True),
        ),
    ]
