# Generated by Django 5.0.6 on 2024-06-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_filter',
        ),
    ]
